
import { Property, Client, PropertyType, TransactionType, PropertyStatus, FurnishingStatus, LeadStage, ListingSource } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    tenantId: 't1',
    title: 'Modern 3BHK Apartment in Sky Heights',
    description: 'Beautifully designed modern apartment with stunning city views, premium Italian marble flooring, and a dedicated home office space.',
    type: PropertyType.FLAT,
    transactionType: TransactionType.RENT,
    price: 45000,
    negotiable: true,
    carpetArea: 1500,
    builtUpArea: 1800,
    bhk: '3BHK',
    floorNumber: 12,
    totalFloors: 20,
    buildingName: 'Sky Heights',
    facing: 'East',
    ageOfBuilding: 5,
    furnishing: FurnishingStatus.FULLY,
    parking: true,
    liftAvailable: true,
    powerBackup: true,
    petsAllowed: true,
    bachelorsAllowed: false,
    availabilityDate: '2023-12-01',
    status: PropertyStatus.AVAILABLE,
    location: { address: 'Plot 45, Bandra West', area: 'Bandra', city: 'Mumbai' },
    photos: ['https://picsum.photos/seed/prop1/800/600'],
    // Fix: Added listingSource and isFavorite
    listingSource: ListingSource.DIRECT,
    isFavorite: false,
    createdAt: '2023-10-01'
  },
  {
    id: 'p2',
    tenantId: 't1',
    title: 'Luxury Villa with Private Pool',
    description: 'Expansive 5BHK villa with high-end amenities, private gym, and a beautiful landscaped garden in a gated community.',
    type: PropertyType.VILLA,
    transactionType: TransactionType.SALE,
    price: 125000000,
    negotiable: false,
    carpetArea: 4500,
    builtUpArea: 5500,
    bhk: '5BHK',
    floorNumber: 0,
    totalFloors: 2,
    buildingName: 'Palm Groves',
    facing: 'Other',
    ageOfBuilding: 2,
    furnishing: FurnishingStatus.SEMI,
    parking: true,
    liftAvailable: false,
    powerBackup: true,
    petsAllowed: true,
    bachelorsAllowed: true,
    availabilityDate: '2024-01-01',
    status: PropertyStatus.AVAILABLE,
    location: { address: 'Sector 5, Alibaug', area: 'Alibaug', city: 'Raigad' },
    photos: ['https://picsum.photos/seed/prop2/800/600'],
    // Fix: Added listingSource, brokerName and isFavorite
    listingSource: ListingSource.BROKER,
    brokerName: 'Elite Realty',
    isFavorite: true,
    createdAt: '2023-09-15'
  }
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    tenantId: 't1',
    name: 'Rohit Sharma',
    email: 'rohit.s@example.com',
    phone: '+91 9876543210',
    description: 'Looking for a high-floor apartment with a sea view. Prefer quiet neighborhoods and modern amenities.',
    maritalStatus: 'Married',
    familySize: 4,
    requirement: TransactionType.RENT,
    preferredAreas: ['Bandra', 'Andheri'],
    preferredCity: 'Mumbai',
    bhkPreference: ['2BHK', '3BHK'],
    furnishingPreference: [FurnishingStatus.FULLY, FurnishingStatus.SEMI],
    budgetMin: 30000,
    budgetMax: 50000,
    moveInDate: '2023-12-15',
    leadStage: LeadStage.SITE_VISIT,
    tags: ['High Priority', 'Family'],
    // Fix: Added isFavorite
    isFavorite: true,
    createdAt: '2023-10-10'
  },
  {
    id: 'c2',
    tenantId: 't1',
    name: 'Anjali Gupta',
    email: 'anjali.g@example.com',
    phone: '+91 8877665544',
    description: 'Investor looking for luxury properties in vacation spots. Interested in holiday homes with rental yield potential.',
    maritalStatus: 'Bachelor',
    familySize: 1,
    requirement: TransactionType.SALE,
    preferredAreas: ['Juhu', 'Alibaug'],
    preferredCity: 'Mumbai',
    bhkPreference: ['4BHK', '5BHK'],
    furnishingPreference: [FurnishingStatus.SEMI, FurnishingStatus.UNFURNISHED],
    budgetMin: 80000000,
    budgetMax: 150000000,
    moveInDate: '2024-02-01',
    leadStage: LeadStage.NEGOTIATION,
    tags: ['Investor', 'Luxury'],
    // Fix: Added isFavorite
    isFavorite: false,
    createdAt: '2023-09-01'
  }
];
